.TH "POSTMARK" "1" "2001-09-13" "russell@coker.com.au" "Postmark"
.SH "NAME"
postmark \- file system benchmark program by NetApp.

.SH "SYNOPSIS"
.B postmark
.RI [config-file]

.SH "DESCRIPTION"
This manual page documents briefly the
.B postmark
program.
.P
When
.B postmark
is run it gives a command\-line interface to configure and run tests.  The
"help" command displays basic information on how to operate it.
.P
The name of a text file containing commands may be specified on the command
line.
.P
The next version of this man page will have more information.
.SH "AUTHOR"
This manual page was written by Russell Coker <russell@coker.com.au>,
for the Debian GNU/Linux system (but may be used by others).
